server-ip=77.111.240.232
server-port=25565
level-name=world
max-players=999
admin-slot=true
allow-flight=false
allow-nether=false
announce-player-achievements=true
difficulty=1
enable-command-block=false
enable-query=false
enable-rcon=false
force-gamemode=false
gamemode=0
generate-structures=true
generator-settings=
grow-trees=true
hardcore=false
hellworld=false
level-seed=
level-type=DEFAULT
max-build-height=256
max-connections=3
motd=
online-mode=true
op-permission-level=4
player-idle-timeout=0
public=true
pvp=true
resource-pack=
server-name=VeryGames.net Minecraft VQS
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
verify-names=true
view-distance=10
white-list=false

hostname "Bungee Server"

