version: '3.5' # git pull && git submodule update --recursive --remote
services:
  # NOTE TO SELF: Ports within network do not use the external port, but their internal ones.
  mysql:
    image: mysql:8.0.15
    restart: always
    command: --default-authentication-plugin=mysql_native_password --init-file /app/fixtures_production.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'o8D2!ld191MGEC01'
      MYSQL_DATABASE: orbitmines_production
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3306"
    volumes:
      - ./db:/app
      - /home/orbitmines/current/database/mysql-data:/var/lib/mysql
  redis:
    image: redis:5.0.3-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
#    volumes:
#      - /home/orbitmines/current/database/redis-data:/data
  bungeecord:
    build:
      context: .
      dockerfile: ./Dockerfile.bungeecord.production
      args:
        om_server_name: bungeecord
        bungeecord_version: LATEST
    depends_on:
      - mysql
      - redis
    environment:
      - OM_ENV=production
      - OM_SERVER_NAME=bungeecord
      - OM_IP=bungeecord
      - OM_PORT=25565
      - OM_XMS=2G
      - OM_XMX=2G
      - OM_DISCORD_SERVER_ID=221293899967102976
      - OM_DISCORD_BOT_TOKEN=
      - OM_DISCORD_BOT_MAIN=true
      - OM_DB_HOST=mysql
      - OM_DB_PORT=3306
      - OM_DB_NAME=orbitmines_production
      - OM_DB_USER=orbitmines
      - OM_DB_PASSWORD=o8D2!ld191MGEC01
      - OM_DB_OPTIONS=?useUnicode=true&amp;useJDBCCompliantTimezoneShift=true&amp;serverTimezone=UTC
      - OM_REDIS_HOST=redis
      - OM_REDIS_PORT=6379
      - OM_REDIS_TIMEOUT=0
      - OM_REDIS_MAX_POOL_SIZE=20
#      - OM_MAX_PLAYERS=300
      - OM_WEBSITE_LINK=https://www.OrbitMines.com
      - OM_SHOP_LINK=https://OrbitMines.buycraft.net
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
      - "8804:8804" # Player Analytics
      - "8192:8192" # Votifier
    command: [sh, -c, "cd /app &&
                             mkdir -p plugins &&
                             cp /build/servers/bungeecord/target/bungeecord-1.0-SNAPSHOT-jar-with-dependencies.jar /app/plugins/bungeecord.jar &&
                             cp /build/bungeecord-jars/LATEST.jar /app/minecraft_server.jar &&
                             cp -a /build/servers/bungeecord/.docker/server_template/. /app &&
                             chmod +x /app/start.sh &&
                             sh start.sh"]
    restart: always
    volumes:
      - .:/build
      - /home/orbitmines/current/servers/bungeecord:/app
      - /home/orbitmines/current/skins:/app/skins # SkinLibrary
  hub:
    build:
      context: .
      dockerfile: ./Dockerfile.spigot.production
      args:
        om_server_name: hub
        space_spigot_version: LATEST
    depends_on:
      - mysql
      - redis
    environment:
      - OM_ENV=production
      - OM_SERVER_NAME=hub
      - OM_IP=hub
      - OM_PORT=25565
      - OM_XMS=4G
      - OM_XMX=4G
      - OM_DISCORD_SERVER_ID=221293899967102976
      - OM_DISCORD_BOT_TOKEN=
      - OM_DISCORD_BOT_MAIN=false
      - OM_DB_HOST=mysql
      - OM_DB_PORT=3306
      - OM_DB_NAME=orbitmines_production
      - OM_DB_USER=orbitmines
      - OM_DB_PASSWORD=o8D2!ld191MGEC01
      - OM_DB_OPTIONS=?useUnicode=true&amp;useJDBCCompliantTimezoneShift=true&amp;serverTimezone=UTC
      - OM_REDIS_HOST=redis
      - OM_REDIS_PORT=6379
      - OM_REDIS_TIMEOUT=0
      - OM_REDIS_MAX_POOL_SIZE=15
      - OM_DISCORD_INVITE_LINK=https://www.OrbitMines.com/discord
      - OM_WEBSITE_LINK=https://www.OrbitMines.com
      - OM_SHOP_LINK=https://OrbitMines.buycraft.net
      - PLAN_URL=http://bungeecord:8804
    stdin_open: true
    tty: true
    ports:
      - "25566:25565"
    command: [sh, -c, "cd /app &&
                             mkdir -p plugins &&
                             cp /build/servers/hub/target/hub-1.0-SNAPSHOT-jar-with-dependencies.jar /app/plugins/hub.jar &&
                             cp /build/space-spigot-jars/LATEST.jar /app/minecraft_server.jar &&
                             cp -a /build/spigot-libraries/.docker/server_template/. /app &&
                             cp -a /build/servers/hub/.docker/server_template/. /app &&
                             chmod +x /app/start.sh &&
                             sh start.sh"]
    restart: always
    volumes:
      - .:/build
      - /home/orbitmines/current/servers/hub:/app
      - /home/orbitmines/current/skins:/app/skins # SkinLibrary
      - ./worlds:/app/worlds # Lobbies & Maps
  survival:
    build:
      context: .
      dockerfile: ./Dockerfile.spigot.production
      args:
        om_server_name: survival
        space_spigot_version: LATEST
    depends_on:
      - mysql
      - redis
    environment:
      - OM_ENV=production
      - OM_SERVER_NAME=survival
      - OM_IP=survival
      - OM_PORT=25565
      - OM_XMS=22G
      - OM_XMX=22G
      - OM_DISCORD_SERVER_ID=221293899967102976
      - OM_DISCORD_BOT_TOKEN=
      - OM_DISCORD_BOT_MAIN=false
      - OM_DB_HOST=mysql
      - OM_DB_PORT=3306
      - OM_DB_NAME=orbitmines_production
      - OM_DB_USER=orbitmines
      - OM_DB_PASSWORD=o8D2!ld191MGEC01
      - OM_DB_OPTIONS=?useUnicode=true&amp;useJDBCCompliantTimezoneShift=true&amp;serverTimezone=UTC
      - OM_REDIS_HOST=redis
      - OM_REDIS_PORT=6379
      - OM_REDIS_TIMEOUT=0
      - OM_REDIS_MAX_POOL_SIZE=15
      - OM_DISCORD_INVITE_LINK=https://www.OrbitMines.com/discord
      - OM_WEBSITE_LINK=https://www.OrbitMines.com
      - OM_SHOP_LINK=https://OrbitMines.buycraft.net
      - PLAN_URL=http://bungeecord:8804
    stdin_open: true
    tty: true
    ports:
      - "25567:25565"
    command: [sh, -c, "cd /app &&
                             mkdir -p plugins &&
                             cp /build/servers/survival/target/survival-1.0-SNAPSHOT-jar-with-dependencies.jar /app/plugins/survival.jar &&
                             cp /build/space-spigot-jars/LATEST.jar /app/minecraft_server.jar &&
                             cp -a /build/spigot-libraries/.docker/server_template/. /app &&
                             cp -a /build/servers/survival/.docker/server_template/. /app &&
                             chmod +x /app/start.sh &&
                             sh start.sh"]
    restart: always
    volumes:
      - .:/build
      - /home/orbitmines/current/servers/survival:/app
      - /home/orbitmines/current/skins:/app/skins # SkinLibrary
      - ./worlds:/app/worlds # Lobbies & Maps
  kitpvp:
    build:
      context: .
      dockerfile: ./Dockerfile.spigot.production
      args:
        om_server_name: kitpvp
        space_spigot_version: LATEST
    depends_on:
      - mysql
      - redis
    environment:
      - OM_ENV=production
      - OM_SERVER_NAME=kitpvp
      - OM_IP=kitpvp
      - OM_PORT=25565
      - OM_XMS=6G
      - OM_XMX=6G
      - OM_DISCORD_SERVER_ID=221293899967102976
      - OM_DISCORD_BOT_TOKEN=
      - OM_DISCORD_BOT_MAIN=false
      - OM_DB_HOST=mysql
      - OM_DB_PORT=3306
      - OM_DB_NAME=orbitmines_production
      - OM_DB_USER=orbitmines
      - OM_DB_PASSWORD=o8D2!ld191MGEC01
      - OM_DB_OPTIONS=?useUnicode=true&amp;useJDBCCompliantTimezoneShift=true&amp;serverTimezone=UTC
      - OM_REDIS_HOST=redis
      - OM_REDIS_PORT=6379
      - OM_REDIS_TIMEOUT=0
      - OM_REDIS_MAX_POOL_SIZE=15
      - OM_DISCORD_INVITE_LINK=https://www.OrbitMines.com/discord
      - OM_WEBSITE_LINK=https://www.OrbitMines.com
      - OM_SHOP_LINK=https://OrbitMines.buycraft.net
      - PLAN_URL=http://bungeecord:8804
    stdin_open: true
    tty: true
    ports:
      - "25568:25565"
    command: [sh, -c, "cd /app &&
                             mkdir -p plugins &&
                             cp /build/servers/kitpvp/target/kitpvp-1.0-SNAPSHOT-jar-with-dependencies.jar /app/plugins/kitpvp.jar &&
                             cp /build/space-spigot-jars/LATEST.jar /app/minecraft_server.jar &&
                             cp -a /build/spigot-libraries/.docker/server_template/. /app &&
                             cp -a /build/servers/kitpvp/.docker/server_template/. /app &&
                             chmod +x /app/start.sh &&
                             sh start.sh"]
    restart: always
    volumes:
      - .:/build
      - /home/orbitmines/current/servers/kitpvp:/app
      - /home/orbitmines/current/skins:/app/skins # SkinLibrary
      - ./worlds:/app/worlds # Lobbies & Maps
#  prison:
#    build:
#      context: .
#      dockerfile: ./Dockerfile.spigot.production
#      args:
#        om_server_name: prison
#        space_spigot_version: LATEST
#    depends_on:
#      - mysql
#      - redis
#    environment:
#      - OM_ENV=production
#      - OM_SERVER_NAME=prison
#      - OM_IP=prison
#      - OM_PORT=25565
#      - OM_XMS=1G
#      - OM_XMX=1G
#      - OM_DISCORD_SERVER_ID=221293899967102976
#      - OM_DISCORD_BOT_TOKEN=
#      - OM_DISCORD_BOT_MAIN=false
#      - OM_DB_HOST=mysql
#      - OM_DB_PORT=3306
#      - OM_DB_NAME=orbitmines_production
#      - OM_DB_USER=orbitmines
#      - OM_DB_PASSWORD=o8D2!ld191MGEC01
#      - OM_DB_OPTIONS=?useUnicode=true&amp;useJDBCCompliantTimezoneShift=true&amp;serverTimezone=UTC
#      - OM_REDIS_HOST=redis
#      - OM_REDIS_PORT=6379
#      - OM_REDIS_TIMEOUT=0
#      - OM_REDIS_MAX_POOL_SIZE=15
#      - OM_DISCORD_INVITE_LINK=https://www.OrbitMines.com/discord
#      - OM_WEBSITE_LINK=https://www.OrbitMines.com
#      - OM_SHOP_LINK=https://OrbitMines.buycraft.net
#      - PLAN_URL=http://bungeecord:8804
#    stdin_open: true
#    tty: true
#    ports:
#      - "25569:25565"
#    command: [sh, -c, "cd /app &&
#                             mkdir -p plugins &&
#                             cp /build/servers/prison/target/prison-1.0-SNAPSHOT-jar-with-dependencies.jar /app/plugins/prison.jar &&
#                             cp /build/space-spigot-jars/LATEST.jar /app/minecraft_server.jar &&
#                             cp -a /build/spigot-libraries/.docker/server_template/. /app &&
#                             cp -a /build/servers/prison/.docker/server_template/. /app &&
#                             chmod +x /app/start.sh &&
#                             sh start.sh"]
#    restart: always
#    volumes:
#      - .:/build
#      - /home/orbitmines/current/servers/prison:/app
#      - /home/orbitmines/current/skins:/app/skins # SkinLibrary
#      - ./worlds:/app/worlds # Lobbies & Maps
  build:
    build:
      context: .
      dockerfile: ./Dockerfile.spigot.production
      args:
        om_server_name: build
        space_spigot_version: LATEST
    depends_on:
      - mysql
      - redis
    environment:
      - OM_ENV=production
      - OM_SERVER_NAME=build
      - OM_IP=build
      - OM_PORT=25565
      - OM_XMS=5G
      - OM_XMX=5G
      - OM_DISCORD_SERVER_ID=221293899967102976
      - OM_DISCORD_BOT_TOKEN=
      - OM_DISCORD_BOT_MAIN=false
      - OM_DB_HOST=mysql
      - OM_DB_PORT=3306
      - OM_DB_NAME=orbitmines_production
      - OM_DB_USER=orbitmines
      - OM_DB_PASSWORD=o8D2!ld191MGEC01
      - OM_DB_OPTIONS=?useUnicode=true&amp;useJDBCCompliantTimezoneShift=true&amp;serverTimezone=UTC
      - OM_REDIS_HOST=redis
      - OM_REDIS_PORT=6379
      - OM_REDIS_TIMEOUT=0
      - OM_REDIS_MAX_POOL_SIZE=15
      - OM_DISCORD_INVITE_LINK=https://www.OrbitMines.com/discord
      - OM_WEBSITE_LINK=https://www.OrbitMines.com
      - OM_SHOP_LINK=https://OrbitMines.buycraft.net
      - PLAN_URL=http://bungeecord:8804
    stdin_open: true
    tty: true
    ports:
      - "25570:25565"
    command: [sh, -c, "cd /app &&
                            mkdir -p plugins &&
                            cp /build/servers/build/target/build-1.0-SNAPSHOT-jar-with-dependencies.jar /app/plugins/build.jar &&
                            cp /build/space-spigot-jars/LATEST.jar /app/minecraft_server.jar &&
                            cp -a /build/spigot-libraries/.docker/server_template/. /app &&
                            cp -a /build/servers/build/.docker/server_template/. /app &&
                            chmod +x /app/start.sh &&
                            sh start.sh"]
    restart: always
    volumes:
      - .:/build
      - /home/orbitmines/current/servers/build:/app
      - /home/orbitmines/current/skins:/app/skins # SkinLibrary
      - ./worlds:/app/worlds # Lobbies & Maps
  error-tracker:
    build:
      context: .
      dockerfile: ./Dockerfile.error_tracker.production
    depends_on:
      #      - mysql
      - redis
    environment:
      - OM_ENV=production
      - OM_DISCORD_SERVER_ID=221293899967102976
      - OM_DISCORD_BOT_TOKEN=
      - OM_DISCORD_BOT_MAIN=false
      #      - OM_DB_HOST=mysql
      #      - OM_DB_PORT=3306
      #      - OM_DB_NAME=orbitmines_production
      #      - OM_DB_USER=orbitmines
      #      - OM_DB_PASSWORD=o8D2!ld191MGEC01
      #      - OM_DB_OPTIONS=?useUnicode=true&amp;useJDBCCompliantTimezoneShift=true&amp;serverTimezone=UTC
      - OM_REDIS_HOST=redis
      - OM_REDIS_PORT=6379
      - OM_REDIS_TIMEOUT=0
      - OM_REDIS_MAX_POOL_SIZE=5
    stdin_open: true
    tty: true
    command: [sh, -c, "cd /app &&
                             cp /build/error-tracker/target/ErrorTracker-1.0-SNAPSHOT-jar-with-dependencies.jar /app/error-tracker.jar &&
                             java -jar error-tracker.jar"]
    restart: always
    volumes:
      - .:/build
      - /home/orbitmines/current/servers/hub/logs:/app/servers/hub
      - /home/orbitmines/current/servers/survival/logs:/app/servers/survival
      - /home/orbitmines/current/servers/kitpvp/logs:/app/servers/kitpvp
      - /home/orbitmines/current/servers/prison/logs:/app/servers/prison
      - /home/orbitmines/current/servers/build/logs:/app/servers/build
      - /home/orbitmines/current/servers/bungeecord:/app/servers/bungeecord
      - /home/orbitmines/current/error_logs:/app/error_logs
  server-restarter:
    build:
      context: .
      dockerfile: ./Dockerfile.server_restarter.production
    depends_on:
      - redis
    environment:
      - OM_ENV=production
      - OM_REDIS_HOST=redis
      - OM_REDIS_PORT=6379
      - OM_REDIS_TIMEOUT=0
      - OM_REDIS_MAX_POOL_SIZE=5
      - OM_HUB_TIMEOUT=40
      - OM_SURVIVAL_TIMEOUT=60
      - OM_HOST_IP=144.76.112.55
      - OM_HOST_RESTARTER_USER=server-restarter
    stdin_open: true
    tty: true
    command: [sh, -c, "cd /app &&
                             cp /build/server-restarter/target/ServerRestarter-1.0-SNAPSHOT-jar-with-dependencies.jar /app/server-restarter.jar &&
                             java -jar server-restarter.jar"]
    restart: always
    volumes:
      - .:/build
      - /home/orbitmines/current/server-restarter/.ssh:/root/.ssh
  website:
    build:
      context: .
      dockerfile: ./Dockerfile.website.production
    depends_on:
      - mysql
      - nginx
    #      - redis
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - OM_ENV=production
      - OM_DB_HOST=mysql
      - OM_DB_PORT=3306
      - OM_DB_NAME=orbitmines_production
      - OM_DB_USER=orbitmines
      - OM_DB_PASSWORD=o8D2!ld191MGEC01
      #      - OM_DB_OPTIONS=?useUnicode=true&amp;useJDBCCompliantTimezoneShift=true&amp;serverTimezone=UTC
      - OM_REDIS_HOST=redis
      - OM_REDIS_PORT=6379
    command: [sh, -c, "cd /app && rm -rf tmp/pids/server.pid && rails server -b 0.0.0.0"]
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./website:/app
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx.production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/orbitmines/current/nginx/certs:/etc/nginx/certs