FROM openjdk:8-jdk-alpine

RUN apk update && \
    apk add \
        curl \
        bash \
        maven \
        git \
        dos2unix

# Copy Build Sources
WORKDIR /build
COPY ./global-libraries /build/global-libraries
COPY ./error-tracker /build/error-tracker

WORKDIR /app