#!/bin/bash

cd "${0%/*}"

parent_dir=${PWD}

# Variables
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT_GRAY='\033[0;37m'
DARK_GRAY='\033[1;30m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHT_BLUE='\033[1;34m'
LIGHT_PURPLE='\033[1;35m'
LIGHT_CYAN='\033[1;36m'
WHITE='\033[1;37m'
RESET='\033[0m'

PREFIX="${RESET}[${LIGHT_GRAY}OrbitMines${RESET}]"
CMD="om"
DOCKER_NETWORK="orbitmines"

APPS_S="redis mysql error-tracker website bungeecord hub survival kitpvp build"
APPS=("redis" "mysql" "error-tracker" "website" "bungeecord" "hub" "survival" "kitpvp" "build")
ALL_REQUIREMENTS=("global-libraries" "spigot-libraries")

# Requirements
declare -A REQUIREMENTS
REQUIREMENTS["error-tracker"]="global-libraries"
REQUIREMENTS["servers/bungeecord"]="global-libraries"
REQUIREMENTS["servers/hub"]="global-libraries, spigot-libraries"
REQUIREMENTS["servers/survival"]="global-libraries, spigot-libraries"
REQUIREMENTS["servers/kitpvp"]="global-libraries, spigot-libraries"
REQUIREMENTS["servers/prison"]="global-libraries, spigot-libraries"
REQUIREMENTS["servers/build"]="global-libraries, spigot-libraries"
REQUIREMENTS["website"]=""

function to_parent_dir() {
    cd ${parent_dir}
}

to_parent_dir

function msg() {
    echo -e "${PREFIX} ${1}${2}${RESET}"
}

function msg_available_servers() {
    msg ${LIGHT_PURPLE} "Available Servers"
    for app in "${APPS[@]}"; do
        msg ${RESET} " - ${YELLOW}${app}${RESET}"
    done
}
function msg_incorrect_usage() {
    msg ${LIGHT_RED} "Incorrect usage."
}
function msg_help_update() {
    msg ${BLUE} "${CMD} update <server>|all ${RESET}- Update all server jars in target folder"
}
function msg_help_start() {
    msg ${BLUE} "${CMD} start <server>|all ${RESET}- Start server(s) with requirements"
}
function msg_help_stop() {
    msg ${BLUE} "${CMD} stop <server>|all ${RESET}- Stop server(s)"
}
function msg_help_redis() {
    msg ${BLUE} "${CMD} redis ${RESET}- Enter redis-cli"
}
function msg_help_mysql() {
    msg ${BLUE} "${CMD} mysql ${RESET}- Enter mysql-server"
}

function msg_help() {
    msg ${LIGHT_PURPLE} "Command Help"
    msg_help_update
    msg_help_start
    msg_help_stop
    msg_help_redis
    msg_help_mysql

    msg_available_servers
}

function install() {
    to_parent_dir
    cd ${1}

    msg ${BLUE} "Installing ${1} in ${PWD}..."

    mvn -DargLine=-Dfile.encoding=UTF-8 install
}

function update_requirement() {
    start_time="$(date -u +%s)"

    install ${1}

    end_time="$(date -u +%s)"
    elapsed="$(($end_time-$start_time))"

    msg ${LIGHT_GREEN} "done. ${1} updated in ${elapsed}s."
}
function update() {
    start_time="$(date -u +%s)"
    msg ${BLUE} "Updating ${1}..."

    IFS=', ' read -r -a requirement <<< "${REQUIREMENTS[${1}]}"

    for requirement in "${requirement[@]}"; do
        update_requirement ${requirement}
    done

    install ${1}

    end_time="$(date -u +%s)"
    elapsed="$(($end_time-$start_time))"
    msg ${LIGHT_GREEN} "done. ${1} updated in ${elapsed}s."
}
function update_without_requirements() {
    start_time="$(date -u +%s)"
    msg ${BLUE} "Updating ${1}..."

    install ${1}

    end_time="$(date -u +%s)"
    elapsed="$(($end_time-$start_time))"
    msg ${LIGHT_GREEN} "done. ${1} updated in ${elapsed}s."
}

function update_all() {
    start_time="$(date -u +%s)"
    msg ${BLUE} "Updating all servers..."

    for requirement in "${ALL_REQUIREMENTS[@]}"; do
        update_requirement ${requirement}
    done

    for app in "${APPS[@]}"; do
        if [[ ${app} = "error-tracker" ]]; then
            update_without_requirements "${app}"
        else
            update_without_requirements "servers/${app}"
        fi
    done

    end_time="$(date -u +%s)"
    elapsed="$(($end_time-$start_time))"
    msg ${LIGHT_GREEN} "done. All servers updated in ${elapsed}s."
}

function stop() {
    msg ${RED} "Stopping ${1}..."
    docker-compose kill ${1}
}

function stop_all() {
    msg ${RED} "Stopping all servers..."
    docker-compose kill ${APPS_S}
}

function start() {
    stop ${1}

    msg ${BLUE} "Starting ${1}..."
    docker-compose up -d ${1}
}

function start_all() {
    stop_all
    msg ${BLUE} "Starting all servers..."
    docker-compose up -d
}

# Commands
case "${1,,}" in
    update)
        if [[ $# -eq 2 ]]; then
            if [[ "${2,,}" = "all" ]]; then
                update_all
            else
                for app in "${APPS[@]}"; do
                    if [[ "${2,,}" = ${app} ]]; then
                        if [[ ${app} = "error-tracker" ]] || [[ ${app} = "server-restarter" ]]; then
                            update "${app}"
                        else
                            update "servers/${app}"
                        fi
                    fi
                done
            fi
        else
            msg_incorrect_usage
            msg_help_update
            msg_available_servers
        fi
    ;;
    start)
        if [[ $# -eq 2 ]]; then
            if [[ "${2,,}" = "all" ]]; then
                start_all
            else
                for app in "${APPS[@]}"; do
                    if [[ "${2,,}" = ${app} ]]; then
                        start ${app}
                    fi
                done
            fi
        else
            msg_incorrect_usage
            msg_help_start
            msg_available_servers
        fi
    ;;
    stop)
        if [[ $# -eq 2 ]]; then
            if [[ "${2,,}" = "all" ]]; then
                stop_all
            else
                for app in "${APPS[@]}"; do
                    if [[ "${2,,}" = ${app} ]]; then
                        stop ${app}
                    fi
                done
            fi
        else
            msg_incorrect_usage
            msg_help_stop
            msg_available_servers
        fi
    ;;
    redis)
        msg ${BLUE} "Entering redis-cli..."
        docker exec -it ${DOCKER_NETWORK}_redis_1 redis-cli
    ;;
    mysql)
        msg ${BLUE} "Entering mysql-server..."
        docker exec -it ${DOCKER_NETWORK}_mysql_1 mysql -u root -p
    ;;
    *)
        msg_help
    ;;
esac