#Minecraft server properties
#Fri Jul 11 19:27:19 CEST 2014
player-idle-timeout=0
resource-pack=
view-distance=10
online-mode=true
gamemode=0
difficulty=1
spawn-animals=true
max-players=20
server-ip=
pvp=true
server-port=25565
allow-flight=false
white-list=false
force-gamemode=false
spawn-npcs=true
generate-structures=true
motd=A Minecraft Server
