connection_throttle: 4000
online_mode: true
remote_ping_timeout: 5000
groups: {}
servers:
  some_server:
    motd: ''
    address: 127.0.0.1:25595
    restricted: false
remote_ping_cache: -1
connection_throttle_limit: 3
enforce_secure_profile: false
listeners:
- query_port: 25564
  query_enabled: false
  bind_local_address: true
  tab_list: GLOBAL_PING
  ping_passthrough: false
  force_default_server: false
  proxy_protocol: false
  host: 0.0.0.0:25565
  motd: '&7&lOrbit&8&lMines'
  priorities:
  - some_server
  forced_hosts:
    some_ip: some_server
  max_players: 1
  tab_size: 60
server_connect_timeout: 5000
player_limit: -1
max_packets_per_second: 4096
ip_forward: true
disabled_commands: []
log_pings: true
max_packets_data_per_second: 33554432
forge_support: false
log_commands: false
stats: 3d332267-cc22-4e1e-bab2-608173d4376c
reject_transfers: false
network_compression_threshold: 64
permissions: {}
prevent_proxy_connections: false
timeout: 30000
