name: OrbitMinesMiniGames
author: O_o_Fadi_o_O
version: 1.0.0
description: OrbitMinesMiniGames by O_o_Fadi_o_O
main: fadidev.orbitmines.minigames.OrbitMinesMiniGames
commands:
depend: [OrbitMinesAPI, WorldEdit]