name: OrbitMinesCellGenerator
author: O_o_Fadi_o_O
load: STARTUP
version: 1
description: OrbitMinesCellGenerator by O_o_Fadi_o_O
main: fadidev.orbitmines.generators.cellgenerator.CellGenerator
commands:
depend: [Multiverse-Core]